.TH man 1 "07 November 2013" ".1" "zsub manual"
.SH NAME
zs \- Submit a grid job for each of a set of files
.SH SYNOPSIS
.B zs
[\fIOPTIONS\fR] \fI'FILENAME_PATTERN'\fR \fI'JOB_NAME'\fR \fICOMMAND_NAME\fR [\fIARG_PATTERN\fR]...

.SH DESCRIPTION

.PP
zs takes a set of input files matched by FILENAME_PATTERN and submits grid engine jobs for each of them.

.SH OPTIONS

.TP
\fB\-v\fR
Be verbose; print the assembled command before executing it

.TP
\fB\-d\fR
Dry run; print the assembled command but don't execute it

.SH EXAMPLES

.SH BUGS
No known bugs, but please tell me if you find any: http://github.com/sseemayer/zsub
.SH AUTHOR
Stefan Seemayer (mail@semicolonsoftware.de)
